"""Import the reviewed Eden composition into standalone faction config data."""
import argparse
import json
import re
from pathlib import Path


class Parser:
    def __init__(self, text):
        text = re.sub(r'//[^\n]*', '', text)
        self.tokens = re.findall(r'"(?:""|[^"])*"|[A-Za-z_$][\w$]*|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|[{}\[\]=;,:]', text)
        self.i = 0

    def pop(self, expected=None):
        token = self.tokens[self.i]
        self.i += 1
        if expected is not None and token != expected:
            raise ValueError((expected, token, self.i))
        return token

    def value(self):
        token = self.pop()
        if token == '{':
            result = []
            while self.tokens[self.i] != '}':
                result.append(self.value())
                if self.tokens[self.i] == ',':
                    self.pop(',')
            self.pop('}')
            return result
        if token.startswith('"'):
            return token[1:-1].replace('""', '"')
        return float(token) if any(c in token for c in '.eE') else int(token)

    def node(self):
        result = {}
        while self.i < len(self.tokens) and self.tokens[self.i] != '}':
            key = self.pop()
            if key == 'class':
                key = self.pop()
                if self.tokens[self.i] == ';':
                    self.pop(';')
                    continue
                if self.tokens[self.i] == ':':
                    self.pop(':')
                    self.pop()
                self.pop('{')
                result[key] = self.node()
                self.pop('}')
            else:
                if self.tokens[self.i] == '[':
                    self.pop('[')
                    self.pop(']')
                self.pop('=')
                result[key] = self.value()
            self.pop(';')
        return result


def children(node):
    return [v for v in node.values() if isinstance(v, dict)]


def objects(node):
    if node.get('dataType') == 'Object':
        yield node
    for child in children(node):
        yield from objects(child)


def weapon(node):
    if not node:
        return []
    def mag(key):
        m = node.get(key, {})
        return [m['name'], m['ammoLeft']] if m else []
    return [node.get('name', ''), node.get('muzzle', ''), node.get('flashlight', ''),
            node.get('optics', ''), mag('primaryMuzzleMag'), mag('secondaryMuzzleMag'), node.get('underBarrel', '')]


def container(node):
    if not node:
        return []
    cargo = []
    for kind in ('ItemCargo', 'MagazineCargo', 'WeaponCargo'):
        for item in children(node.get(kind, {})):
            if kind == 'WeaponCargo':
                raise ValueError('Weapon cargo requires explicit review')
            entry = [item['name'], item['count']]
            if kind == 'MagazineCargo':
                entry.append(item['ammoLeft'])
            cargo.append(entry)
    return [node['typeName'], cargo]


def loadout(inv):
    return [weapon(inv.get(k, {})) for k in ('primaryWeapon', 'secondaryWeapon', 'handgun')] + [
        container(inv.get(k, {})) for k in ('uniform', 'vest', 'backpack')] + [
        inv.get('headgear', ''), inv.get('goggles', ''), weapon(inv.get('binocular', {})),
        [inv.get(k, '') for k in ('map', 'gps', 'radio', 'compass', 'watch', 'hmd')]]


def literal(value):
    if isinstance(value, list):
        return '{' + ','.join(literal(v) for v in value) + '}'
    if isinstance(value, str):
        return '"' + value.replace('"', '""') + '"'
    return str(value)


NAMES = [
    ('MissileSpecialist', 'Missile Specialist'), ('Pilot', 'Pilot'), ('TIE', 'TIE Fighter'),
    ('Rifleman', 'Rifleman'), ('LIUS_F', 'LIU (Support)'), ('LIUS_T', 'LIU (Transport)'),
    ('SquadLeader', 'Squad Leader'), ('PKV5', 'PK-V5'), ('RAAT', 'RAAT'),
    ('Speeder74Z', '74-Z Speeder'), ('X34', 'X-34 Landspeeder'), ('ITT', 'ITT'),
    ('LAS_Deserter', 'LA-S (Deserter)'), ('LAS_Z6', 'LA-S (Z-6)'), ('Nu', 'Nu-class Shuttle'),
    ('HK55', 'HK-55 Droid'), ('VWing', 'V-wing'), ('Grenadier', 'Grenadier'),
    ('HeavyGunner', 'Heavy Gunner'), ('Marksman', 'Marksman')]


def generate(data, unique, source):
    root = Path(__file__).resolve().parents[1]
    out = root / 'TAEMiningGuild'
    out.mkdir(exist_ok=True)
    header = Parser(source.with_name('header.sqe').read_text(encoding='utf-8-sig')).node()
    variants = list(unique.values())
    if len(variants) != len(NAMES):
        raise ValueError('Composition changed: review role mapping before importing')
    classes = ['TAE_MiningGuild_' + suffix for suffix, _ in NAMES]
    deps = list(dict.fromkeys(header['requiredAddons'] + ['cba_xeh']))
    lines = ['// Generated by tools/import-mining-guild.py; do not edit loadouts by hand.',
             'class CfgPatches { class TAEMiningGuild {',
             'name="TAE Mining Guild"; author="Havoc (composition)"; requiredVersion=2.18;',
             'requiredAddons[]=' + literal(deps) + ';', 'units[]=' + literal(classes) + '; weapons[]={}; }; };',
             'class CfgFactionClasses { class TAE_Faction_MiningGuild { displayName="[TAE] Mining Guild"; side=0; priority=2; }; };',
             'class CfgEditorCategories { class TAE_EdCat_MiningGuild { displayName="[TAE] Mining Guild"; }; };',
             'class CfgFunctions { class TAE { class MiningGuild { file="TAEMiningGuild\\functions"; class initMiningGuild {}; }; }; };',
             'class CfgVehicles {']
    for base in dict.fromkeys(v['type'] for v in variants):
        lines.append(f'class {base};')
    ids = {}
    report = []
    for i, item in enumerate(variants):
        cls = classes[i]
        inv = item.get('Attributes', {}).get('Inventory', {})
        lines.extend([f'class {cls}: {item["type"]} {{', 'scope=2; scopeCurator=2; side=0; faction="TAE_Faction_MiningGuild";',
                      'editorCategory="TAE_EdCat_MiningGuild";',
                      'displayName=' + literal(NAMES[i][1]) + ';'])
        # Existing assets retain upstream authors. Composition attribution is separate.
        lines.append('TAE_compositionAuthor="Havoc";')
        if inv:
            gear = loadout(inv)
            lines.append('TAE_loadout[]=' + literal(gear) + ';')
            lines.append('uniformClass=' + literal(inv.get('uniform', {}).get('typeName', '')) + ';')
            lines.append('backpack=' + literal(inv.get('backpack', {}).get('typeName', '')) + ';')
            weapons = [v[0] for v in gear[:3] + [gear[8]] if v] + ['Throw', 'Put']
            linked = [x for x in [inv.get('vest', {}).get('typeName', ''), gear[6], gear[7]] + gear[9] if x]
            magazines = []
            items = []
            for w in gear[:3] + [gear[8]]:
                if w:
                    magazines.extend(m[0] for m in w[4:6] if m)
            for slot in ('uniform', 'vest', 'backpack'):
                c = inv.get(slot, {})
                for m in children(c.get('MagazineCargo', {})):
                    magazines.extend([m['name']] * m['count'])
                for m in children(c.get('ItemCargo', {})):
                    items.extend([m['name']] * m['count'])
            for prop, val in [('weapons', weapons), ('linkedItems', linked), ('magazines', magazines), ('items', items)]:
                lines.append(prop + '[]=' + literal(val) + ';')
                lines.append('respawn' + prop[0].upper() + prop[1:] + '[]=' + literal(val) + ';')
            lines.append('editorSubcategory="EdSubcat_Personnel";')
        elif item['type'] != 'SFA_KOTOR_HK55':
            pilot = i in (2, 12, 13, 14, 16)
            category = 'EdSubcat_Planes' if i in (2, 16) else 'EdSubcat_Helicopters' if pilot else 'EdSubcat_Tanks' if i in (7, 8) else 'EdSubcat_Cars'
            lines.append('editorSubcategory=' + literal(category) + ';')
            lines.append('crew=' + literal(classes[1 if pilot else 3]) + ';')
            lines.append('typicalCargo[]=' + literal([classes[1 if pilot else 3]]) + ';')
        else:
            lines.append('editorSubcategory="EdSubcat_Personnel";')
        for attr in children(item.get('CustomAttributes', {})):
            prop = attr.get('property')
            if prop in ('speaker', 'pitch'):
                lines.append('TAE_' + prop + '=' + literal(attr['Value']['data']['value']) + ';')
            elif prop == 'VehicleCustomization':
                skin = item['Attributes']['textures']
                lines.append('textureList[]=' + literal([skin, 1]) + ';')
                lines.append('TAE_textureSource=' + literal(skin) + ';')
            else:
                raise ValueError(f'Unreviewed custom attribute {prop}')
        lines.append('};')
        key = json.dumps([item['type'], inv, item.get('CustomAttributes', {})], sort_keys=True)
        ids[key] = cls
        report.append(f'| {NAMES[i][1]} | `{cls}` | `{item["type"]}` |')
    lines.append('};')
    lines.append('class Extended_Init_EventHandlers {')
    for cls in classes:
        lines.append(f'class {cls} {{ class TAE_MiningGuild {{ init="_this call TAE_fnc_initMiningGuild"; }}; }};')
    lines.append('};')
    lines.append('class CfgGroups { class East { class TAE_Faction_MiningGuild { name="[TAE] Mining Guild"; class Infantry { name="Infantry";')
    seen_groups = set()
    group_number = 0
    for group in children(data['items']):
        if group.get('dataType') != 'Group' or group.get('CrewLinks'):
            continue
        units = list(objects(group))
        roster = tuple(ids[json.dumps([u['type'], u.get('Attributes', {}).get('Inventory', {}), u.get('CustomAttributes', {})], sort_keys=True)] for u in units)
        if len(roster) < 2 or roster in seen_groups:
            continue
        seen_groups.add(roster)
        group_number += 1
        lines.append(f'class TAE_MiningGuild_Group{group_number} {{ name="Mining Guild Team {group_number} ({len(roster)})"; side=0; faction="TAE_Faction_MiningGuild";')
        for j, cls in enumerate(roster):
            lines.append(f'class Unit{j} {{ side=0; vehicle="{cls}"; rank="' + ('SERGEANT' if j == 0 else 'PRIVATE') + f'"; position[]={{{j % 2 * 5},-{j * 5},0}}; }};')
        lines.append('};')
    lines.append('}; }; }; };')
    (out / 'config.cpp').write_text('\n'.join(lines) + '\n', encoding='utf-8')
    (root / 'docs/mining-guild.md').write_text('# Mining Guild\n\nOPFOR faction imported from Havoc\'s Workshop composition [3805843285](https://steamcommunity.com/sharedfiles/filedetails/?id=3805843285). The downloaded header credits Hondo; the user identifies the creator as Havoc. Original model/texture authors remain inherited. No new armor textures are created.\n\n64 placements deduplicate to 20 classes: 8 personnel and 12 vehicles. Original mod classes are not modified. Requires the composition\'s listed mods; the Workshop composition itself is not required at runtime.\n\n| Entry | TAE classname | Source class |\n|---|---|---|\n' + '\n'.join(report) + f'\n\n{group_number} unique multi-unit infantry formations also appear under OPFOR / Mining Guild. Empty vehicle placement remains empty; standard crewed placement uses guild pilot/rifleman crew.\n\nLoadouts retain container contents, ammunition counts, and weapon attachments. Vehicle skin choices retained: RAAT `bare`, ITT `Tex_ITT_base`. Init code is not copied or executed from the composition.\n\nValidation: config compilation and importer checks; Eden/Zeus preview, dedicated server spawning, respawn and JIP still require in-game testing.\n', encoding='utf-8')


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('composition', type=Path)
    parser.add_argument('--generate', action='store_true')
    args = parser.parse_args()
    data = Parser(args.composition.read_text(encoding='utf-8-sig')).node()
    entries = list(objects(data))
    unique = {}
    for item in entries:
        inv = item.get('Attributes', {}).get('Inventory', {})
        key = json.dumps([item['type'], inv, item.get('CustomAttributes', {})], sort_keys=True)
        unique.setdefault(key, item)
    for n, item in enumerate(unique.values()):
        inv = item.get('Attributes', {}).get('Inventory', {})
        if inv:
            loadout(inv)
        print(n, item['id'], item['type'], inv.get('uniform', {}).get('typeName', ''), inv.get('headgear', ''), inv.get('primaryWeapon', {}).get('name', ''), json.dumps(item.get('CustomAttributes', {})))
    print(f'{len(entries)} placed objects; {len(unique)} unique variants')
    if args.generate:
        generate(data, unique, args.composition)


if __name__ == '__main__':
    main()
