params ["_unit"];
if (!local _unit || {_unit getVariable ["TAE_miningGuildInitialized", false]}) exitWith {};
_unit setVariable ["TAE_miningGuildInitialized", true];
private _config = configOf _unit;
private _loadout = getArray (_config >> "TAE_loadout");
if (_loadout isNotEqualTo []) then {_unit setUnitLoadout [_loadout, false];};
if (isText (_config >> "TAE_speaker")) then {_unit setSpeaker getText (_config >> "TAE_speaker");};
if (isNumber (_config >> "TAE_pitch")) then {_unit setPitch getNumber (_config >> "TAE_pitch");};
private _skin = getText (_config >> "TAE_textureSource");
if (_skin != "") then {[_unit, [_skin, 1], [], true] call BIS_fnc_initVehicle;};
