params ["_logic"];
disableSerialization;
private _data = _logic getVariable ["TAE_requisitionData", []];
if (_data isEqualTo []) exitWith {};
_data params ["_terminal", "_pad", "_classes", "_radius"];
private _near = (nearestObjects [_pad, ["Air"], _radius, true]) select {alive _x && {abs ((getPosASL _x # 2) - (getPosASL _pad # 2)) < 15}};
if (count _near != 1) exitWith {systemChat "[Aircraft Service] Exactly one aircraft must be on the pad.";};
private _vehicle = _near # 0;
private _pylons = getAllPylonsInfo _vehicle;
if (_pylons isEqualTo []) exitWith {systemChat "[Aircraft Service] This aircraft has no pylons.";};
private _display = (findDisplay 46) createDisplay "RscDisplayEmpty";
_display setVariable ["TAE_context", [_logic, _vehicle, _pylons]];
private _background = _display ctrlCreate ["RscText", 100];
_background ctrlSetPosition [0.15, 0.3, 0.7, 0.3];
_background ctrlSetBackgroundColor [0,0,0,0.95];
_background ctrlCommit 0;
private _pylon = _display ctrlCreate ["RscCombo", 101];
_pylon ctrlSetPosition [0.17,0.32,0.66,0.05]; _pylon ctrlCommit 0;
private _store = _display ctrlCreate ["RscCombo", 102];
_store ctrlSetPosition [0.17,0.4,0.66,0.05]; _store ctrlCommit 0;
_pylon ctrlAddEventHandler ["LBSelChanged", {
    params ["_ctrl", "_index"];
    private _display = ctrlParent _ctrl;
    (_display getVariable "TAE_context") params ["_logic", "_vehicle", "_pylons"];
    private _store = _display displayCtrl 102;
    lbClear _store;
    _store lbAdd "Empty pylon"; _store lbSetData [0, ""];
    {
        private _row = _store lbAdd getText (configFile >> "CfgMagazines" >> _x >> "displayName");
        _store lbSetData [_row, _x];
    } forEach (_vehicle getCompatiblePylonMagazines ((_pylons # _index) # 0));
    _store lbSetCurSel 0;
}];
{_pylon lbAdd (_x # 1);} forEach _pylons;
_pylon lbSetCurSel 0;
private _apply = _display ctrlCreate ["RscButton", 103];
_apply ctrlSetText "Install (30 seconds)";
_apply ctrlSetPosition [0.17,0.51,0.39,0.06]; _apply ctrlCommit 0;
_apply ctrlAddEventHandler ["ButtonClick", {
    private _display = ctrlParent (_this # 0);
    (_display getVariable "TAE_context") params ["_logic", "_vehicle", "_pylons"];
    private _index = lbCurSel (_display displayCtrl 101);
    private _store = _display displayCtrl 102;
    if (_index < 0 || {lbCurSel _store < 0}) exitWith {};
    ["TAE_aircraftRequest", [_logic, player, "pylon", [_vehicle, (_pylons # _index) # 0, _store lbData lbCurSel _store]]] call CBA_fnc_serverEvent;
    _display closeDisplay 1;
}];
private _cancel = _display ctrlCreate ["RscButton", 104];
_cancel ctrlSetText "Cancel";
_cancel ctrlSetPosition [0.59,0.51,0.24,0.06]; _cancel ctrlCommit 0;
_cancel ctrlAddEventHandler ["ButtonClick", {(ctrlParent (_this # 0)) closeDisplay 2;}];
